[package]
name = "individual_project_2_yl"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "^0.11.27", features = ["blocking"] }
rusqlite = "^0.29.0"
csv = "^1.3.0"
assert_cmd = "^2.0.16"
predicates = "0.9"  
sys-info = "0.9"